services:
  minio:
    container_name: minIO
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: dev_user
      MINIO_ROOT_PASSWORD: dev_password
    networks:
      - minio-sample
    volumes:
      - minio-storage:/data

volumes:
  minio-storage:

networks:
  minio-sample:
    driver: bridge
